on:
  push:
    branches: ['master']

jobs:
  deployment:
    environment: production
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Prepare repository
        run: git fetch --unshallow --tags
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build CLI
        run: npm run build:main
      - name: Release
        run: npm run release --gitUser @sladg --gitEmail jan@ssoukup.com
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
